plugins {
    java
}

group = "dev.hokagy"
version = "1.beta"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
}

val targetJavaVersion = 21
java {
    val version = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = version
    targetCompatibility = version
    if (JavaVersion.current() < version) {
        toolchain.languageVersion.set(JavaLanguageVersion.of(targetJavaVersion))
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.release.set(targetJavaVersion)
}

tasks.jar {
    archiveFileName.set("NovaCassino-${project.version}.jar")
}
