plugins {
    id 'java'
}

group = 'dev.hokagy'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7'
}

def targetJavaVersion = 21
java {
    def version = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = version
    targetCompatibility = version
    if (JavaVersion.current() < version) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = targetJavaVersion
}

tasks.named('jar', Jar) {
    archiveFileName = "NovaCassino-${project.version}.jar"
}
