# ====================================================== #
#               NovaCassino Configuration                #
#                 Автор: Hokagydev                       #
# ====================================================== #

# Автоматически сохраняемые станции казино (не редактируйте вручную без необходимости)
stations: {}
