name: NovaCassino
version: 1.0.0
main: dev.hokagy.novacassino.NovaCassino
api-version: '1.21'
author: Hokagydev
softdepend: [Vault]

commands:
  procasino:
    description: Главная команда управления NovaCassino
    aliases: [novacasino, casino]

permissions:
  procasino.command.about:
    default: true
  procasino.command.add:
    default: op
  procasino.command.delete:
    default: op
  procasino.command.teleport:
    default: op
  procasino.command.list:
    default: op
  procasino.command.reload:
    default: op
  procasino.command.set:
    default: op
