name: NovaCassino
version: 1.0.0
main: dev.hokagy.novacassino.NovaCassino
api-version: '1.21'
depend: [Vault]

commands:
  procasino:
    description: Главная команда плагина NovaCassino
    aliases: [novacassino]
    permission: procasino.command
